version: "3.4"
services:
  geth:
    image: ethereum/client-go
    command:
      - --datadir
      - test-chain-dir
      - --http
      - --ws
      - --dev
      - --http.api=eth,net,web3,txpool,admin,debug
      - --ws.api=eth,net,web3,txpool,admin,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws.addr=0.0.0.0
      - --http.corsdomain
      - "*"
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - .:/data
  blockscout:
    command:
      - /bin/sh 
      - -c 
      - "mix do ecto.create, ecto.migrate; mix phx.server"
    image: ghcr.io/elek/blockscout
    environment:
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_WS_URL: ws://geth:8546
      ETHEREUM_JSONRPC_HTTP_URL: http://geth:8545
      DATABASE_URL: postgresql://postgres:@postgres:5432/explorer?ssl=false
    ports: 
      - 4000:4000
  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
