- name: STORJ
  address: 0x8098165d982765097e4aa17138816e5b95f9fdb5
  abi: ../test/Gold.abi
  type: ""
  chainid: 4
- name: PIN
  address: 0xe7b556AB490C931dcc3319B56fC83B0628AE21bb
  abi: ../contract/StorjPin.abi
  type: ""
  chainid: 4
- name: NFT
  address: 0xE2908427fBE622Cf2B5c0Ea4E9Bb43C8f04e82CF
  abi: ../test/NFT.abi
  type: ""
  chainid: 4
