- name: STORJ
  address: 0x8098165d982765097e4aa17138816e5b95f9fdb5
  abi: ../test/Gold.abi
  type: ""
  chainid: 4
- name: PIN
  address: 0xBfB4b0112E50D56183a554e8850dDDDC2a6F2a2D
  abi: ../contract/StorjPin.abi
  type: ""
  chainid: 4
