-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE nodes (
	cid text NOT NULL,
	days integer NOT NULL,
	pinned_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( cid )
);
CREATE TABLE pins (
	tx text NOT NULL,
	ix integer NOT NULL,
	cid text NOT NULL,
	retry integer NOT NULL DEFAULT 0,
	error text NOT NULL DEFAULT '',
	parse boolean NOT NULL DEFAULT false,
	amount text NOT NULL,
	processed boolean NOT NULL DEFAULT false,
	created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY ( tx, ix )
);
