name: build
on:
  push: []
jobs:
  build-info:
    runs-on: ubuntu-18.04
    steps:
      - name: chekout
        uses: actions/checkout@v2
      - name: build
        run: ./image-build.sh
      - name: push
        run: ./image-push.sh
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
